# Generated by Django 3.0.3 on 2020-04-11 23:26

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nroencuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=254)),
                ('apellido', models.CharField(max_length=254)),
                ('correo', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=254, null=True)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Numero de contacto', max_length=31, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PregServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.IntegerField(choices=[('5', 'Excelente'), ('4', 'Bueno'), ('3', 'Regular'), ('2', 'Deficiente'), ('1', 'Malo')], default='5', help_text='Seleccione una opccion')),
                ('presentacion', models.IntegerField(choices=[('5', 'Excelente'), ('4', 'Bueno'), ('3', 'Regular'), ('2', 'Deficiente'), ('1', 'Malo')], default='5', help_text='Seleccione una opccion')),
                ('sabor', models.IntegerField(choices=[('5', 'Excelente'), ('4', 'Bueno'), ('3', 'Regular'), ('2', 'Deficiente'), ('1', 'Malo')], default='5', help_text='Seleccione una opccion')),
                ('temperatura', models.IntegerField(choices=[('5', 'Excelente'), ('4', 'Bueno'), ('3', 'Regular'), ('2', 'Deficiente'), ('1', 'Malo')], default='5', help_text='Seleccione una opccion')),
                ('eficiencia', models.IntegerField(choices=[('5', 'Excelente'), ('4', 'Bueno'), ('3', 'Regular'), ('2', 'Deficiente'), ('1', 'Malo')], default='5', help_text='Seleccione una opccion')),
                ('agilidad', models.IntegerField(choices=[('5', 'Excelente'), ('4', 'Bueno'), ('3', 'Regular'), ('2', 'Deficiente'), ('1', 'Malo')], default='5', help_text='Seleccione una opccion')),
                ('ambientacion', models.IntegerField(choices=[('5', 'Excelente'), ('4', 'Bueno'), ('3', 'Regular'), ('2', 'Deficiente'), ('1', 'Malo')], default='5', help_text='Seleccione una opccion')),
                ('nroencuesta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
        ),
    ]
