# Generated by Django 3.0.3 on 2020-04-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200411_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregservicio',
            name='calidad',
            field=models.IntegerField(choices=[('5', 'Excelente'), ('4', 'Bueno'), ('3', 'Regular'), ('2', 'Deficiente'), ('1', 'Malo')], default='5', help_text='Seleccione una opccion'),
        ),
    ]
