# Generated by Django 3.0.3 on 2020-04-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200411_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregservicio',
            name='agilidad',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='ambientacion',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='calidad',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='eficiencia',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='presentacion',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='sabor',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='temperatura',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', help_text='Seleccione una opccion'),
        ),
    ]
