# Generated by Django 3.0.3 on 2020-04-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200411_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregservicio',
            name='agilidad',
        ),
        migrations.RemoveField(
            model_name='pregservicio',
            name='ambientacion',
        ),
        migrations.RemoveField(
            model_name='pregservicio',
            name='eficiencia',
        ),
        migrations.RemoveField(
            model_name='pregservicio',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='pregservicio',
            name='sabor',
        ),
        migrations.RemoveField(
            model_name='pregservicio',
            name='temperatura',
        ),
    ]
