# Generated by Django 3.0.3 on 2020-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200413_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregservicio',
            name='calidad',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion'),
        ),
    ]
