# Generated by Django 3.0.3 on 2020-04-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200413_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregservicio',
            name='agilidad',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AddField(
            model_name='pregservicio',
            name='ambientacion',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AddField(
            model_name='pregservicio',
            name='eficiencia',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AddField(
            model_name='pregservicio',
            name='presentacion',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AddField(
            model_name='pregservicio',
            name='sabor',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion'),
        ),
        migrations.AddField(
            model_name='pregservicio',
            name='temperatura',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion'),
        ),
    ]
