# Generated by Django 3.0.3 on 2020-04-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200413_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregservicio',
            name='nroencuesta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Usuario', unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nroencuesta',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
