# Generated by Django 3.0.3 on 2020-04-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200413_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregExpectativas',
            fields=[
                ('nroencuesta', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Usuario')),
                ('expectativa', models.CharField(choices=[('Totalmente', 'Totalmente'), ('Parcialmente', 'Parcialmente'), ('No se cumplieron', 'No se cumplieron')], help_text='Seleccione una opccion segun las expectativas obtenidas', max_length=254)),
                ('motivo', models.CharField(max_length=254)),
                ('prox_visita', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='agilidad',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='ambientacion',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='calidad',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='eficiencia',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='presentacion',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='sabor',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio'),
        ),
        migrations.AlterField(
            model_name='pregservicio',
            name='temperatura',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio'),
        ),
    ]
