# Generated by Django 3.0.3 on 2020-04-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200413_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregExperiencia',
            fields=[
                ('nroencuesta', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Usuario')),
                ('experiencia', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], help_text='Seleccione una opccion si algun funcionario hizo si experiencia mas agradable', max_length=254)),
                ('funcionario', models.CharField(blank=True, help_text='En caso que sea SI, por favor escribir el nombre del colaborador', max_length=254, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
