# Generated by Django 3.0.3 on 2020-04-14 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pregexperiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('nroencuesta', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Usuario')),
                ('calidad', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio')),
                ('presentacion', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio')),
                ('sabor', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio')),
                ('temperatura', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio')),
                ('eficiencia', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio')),
                ('agilidad', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio')),
                ('ambientacion', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bueno'), (3, 'Regular'), (2, 'Deficiente'), (1, 'Malo')], default='5', help_text='Seleccione una opccion segun la satisfacción del servicio')),
                ('expectativa', models.CharField(choices=[('Totalmente', 'Totalmente'), ('Parcialmente', 'Parcialmente'), ('No se cumplieron', 'No se cumplieron')], help_text='Seleccione una opccion segun las expectativas obtenidas', max_length=254)),
                ('motivo', models.CharField(max_length=254)),
                ('prox_visita', models.CharField(blank=True, max_length=254, null=True)),
                ('experiencia', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], help_text='Seleccione una opccion si algun funcionario hizo si experiencia mas agradable', max_length=254)),
                ('funcionario', models.CharField(blank=True, help_text='En caso que sea SI, por favor escribir el nombre del colaborador', max_length=254, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pregexperiencia',
            name='nroencuesta',
        ),
        migrations.RemoveField(
            model_name='pregservicio',
            name='nroencuesta',
        ),
        migrations.DeleteModel(
            name='PregExpectativas',
        ),
        migrations.DeleteModel(
            name='PregExperiencia',
        ),
        migrations.DeleteModel(
            name='PregServicio',
        ),
    ]
